#include "grace/common.hpp"

namespace grace {

auto to_string(VkResult result) -> const char*
{
#define RESULT_CASE(X) \
  case VK_##X:         \
    return #X

  switch (result) {
    RESULT_CASE(SUCCESS);
    RESULT_CASE(NOT_READY);
    RESULT_CASE(TIMEOUT);
    RESULT_CASE(EVENT_SET);
    RESULT_CASE(EVENT_RESET);
    RESULT_CASE(INCOMPLETE);
    RESULT_CASE(ERROR_OUT_OF_HOST_MEMORY);
    RESULT_CASE(ERROR_OUT_OF_DEVICE_MEMORY);
    RESULT_CASE(ERROR_INITIALIZATION_FAILED);
    RESULT_CASE(ERROR_DEVICE_LOST);
    RESULT_CASE(ERROR_MEMORY_MAP_FAILED);
    RESULT_CASE(ERROR_LAYER_NOT_PRESENT);
    RESULT_CASE(ERROR_EXTENSION_NOT_PRESENT);
    RESULT_CASE(ERROR_FEATURE_NOT_PRESENT);
    RESULT_CASE(ERROR_INCOMPATIBLE_DRIVER);
    RESULT_CASE(ERROR_TOO_MANY_OBJECTS);
    RESULT_CASE(ERROR_FORMAT_NOT_SUPPORTED);
    RESULT_CASE(ERROR_FRAGMENTED_POOL);
    RESULT_CASE(ERROR_UNKNOWN);
    RESULT_CASE(ERROR_OUT_OF_POOL_MEMORY);
    RESULT_CASE(ERROR_INVALID_EXTERNAL_HANDLE);
    RESULT_CASE(ERROR_FRAGMENTATION);
    RESULT_CASE(ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
    RESULT_CASE(PIPELINE_COMPILE_REQUIRED);
    RESULT_CASE(ERROR_SURFACE_LOST_KHR);
    RESULT_CASE(ERROR_NATIVE_WINDOW_IN_USE_KHR);
    RESULT_CASE(SUBOPTIMAL_KHR);
    RESULT_CASE(ERROR_OUT_OF_DATE_KHR);
    RESULT_CASE(ERROR_INCOMPATIBLE_DISPLAY_KHR);
    RESULT_CASE(ERROR_VALIDATION_FAILED_EXT);
    RESULT_CASE(ERROR_INVALID_SHADER_NV);
    RESULT_CASE(ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
    RESULT_CASE(ERROR_NOT_PERMITTED_KHR);
    RESULT_CASE(ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);
    RESULT_CASE(THREAD_IDLE_KHR);
    RESULT_CASE(THREAD_DONE_KHR);
    RESULT_CASE(OPERATION_DEFERRED_KHR);
    RESULT_CASE(OPERATION_NOT_DEFERRED_KHR);
    RESULT_CASE(ERROR_COMPRESSION_EXHAUSTED_EXT);
    RESULT_CASE(RESULT_MAX_ENUM);
    default:
      return "???";
  }
}

}  // namespace grace